#!/bin/bash

paths=($(< paths))
count=1
pct=20000
met="max"

while getopts "c:p:m:" o; do
	case $o in
		c)
			count=$OPTARG
			;;
		p)
			pct=$OPTARG
			;;
		m)
			met=$OPTARG
			;;
	esac
done

if [ $count -gt ${#paths[*]} ]; then
	count=${#paths[*]}
fi

i=0
while [ $i -lt $count ]; do
	echo "Path: ${paths[$i]}   Count: $pct"
	./submit_test_data.sh -p ${paths[$i]} -c $pct >/dev/null 2>&1 &
	((i++))
done

SECONDS=$(date +%s)

echo -n "Waiting for sync... "
sleep 30
echo "done."

echo "${paths[0]} $(($SECONDS - 50)) $SECONDS $met json" | nc 127.0.0.1 3802

