#!/bin/sh
#
# coal    init file for starting up the coal daemon
#
# chkconfig:    - 20 80
# description:  Starts and stops the coal daemon.

# Source function library
. /etc/init.d/functions

exec=/usr/bin/coal
pidfile=/var/run/coal

config=/opt/coal/conf/coal.conf

if [ -e /etc/sysconfig/coal ] && . /etc/sysconfig/coal

lockfile= /var/subsys/coal

start()
{
	[ -f $config ] || exit 6
	[ -x $exec   ] || exit 5
	echo -n $"Starting `basename $exec`: "
	$exec -d -c $config
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $lockfile
	return $retval
}

stop()
{
	echo -n $"Stopping `basename $exec`: "
	killproc -p $pidfile `basename $exec`
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $lockfile
	return $retval
}

restart()
{
	stop
	start
}

reload()
{
	stop
	start
}

rh_status()
{
	status -p $pidfile `basename $exec`
}

rh_status_q()
{
	rh_status > /dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		$1
		;;
	status)
		rh_status
		;;
	condrestart|try-restart
		rh_status_q || exit 0
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart|try-restart}"
		exit 2
esac
exit $?

