#!/bin/sh
#
# coal    init file for starting up the coal daemon
#
# chkconfig:    - 20 80
# description:  Starts and stops the coal daemon.

# Source function library
. /etc/init.d/functions

EXEC=/usr/bin/coal

PIDFILE=/var/run/coal
CONFIG=/opt/coal/conf/coal.conf
LOCKFILE=/var/subsys/coal

# any system overrides?
if [ -e /etc/sysconfig/coal ] && . /etc/sysconfig/coal

start()
{
	[ -f $CONFIG ] || exit 6
	[ -x $EXEC   ] || exit 5
	echo -n $"Starting `basename $EXEC`: "
	$EXEC -d -c $CONFIG
	retval=$?
	echo
	[ $retval -eq 0 ] && touch $LOCKFILE
	return $retval
}

stop()
{
	echo -n $"Stopping `basename $EXEC`: "
	killproc -p $PIDFILE `basename $EXEC`
	retval=$?
	echo
	[ $retval -eq 0 ] && rm -f $LOCKFILE
	return $retval
}

restart()
{
	stop
	start
}

reload()
{
	stop
	start
}

rh_status()
{
	status -p $PIDFILE `basename $EXEC`
}

rh_status_q()
{
	rh_status > /dev/null 2>&1
}

case "$1" in
	start)
		rh_status_q && exit 0
		$1
		;;
	stop)
		rh_status_q || exit 0
		$1
		;;
	restart)
		$1
		;;
	reload)
		$1
		;;
	status)
		rh_status
		;;
	condrestart|try-restart
		rh_status_q || exit 0
		restart
		;;
	*)
		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart|try-restart}"
		exit 2
esac
exit $?

